import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/helpers";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(outfit.className, "h-full antialiased")}>
      <body>{children}</body>
    </html>
  );
}
