import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers";
import { cn } from "@/shared/lib";
import "react-loading-skeleton/dist/skeleton.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(outfit.className, "h-full antialiased")}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
